<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Adds the email-outreach pipeline columns to lead_opportunities.
 *
 * Lifecycle of the outreach state (independent of the lead's own
 * status — a lead can be 'confident' AND have a draft 'approved'):
 *
 *   none           — default; no draft generated yet
 *   draft_pending  — draft generated by AI, waiting manager review
 *   approved       — manager reviewed + approved; ready to send
 *   sent           — send button clicked, email pushed through SMTP
 *   rejected       — manager decided this lead shouldn't be emailed
 *
 * Why "approved" before "sent" instead of one-click:
 *   • External-customer emails are reputation-bearing — we want a
 *     deliberate gesture before SMTP fires.
 *   • The send step records who pressed it (sent_by_user_id) so the
 *     audit trail names a human, not the cron.
 *   • An approved draft can stew if the manager changes their mind
 *     before clicking send.
 *
 * Idempotency: hasColumn checks let us re-run on partially-migrated
 * databases (we got bitten before during the SAP migration; same
 * pattern here).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('lead_opportunities', function (Blueprint $t) {
            if (!Schema::hasColumn('lead_opportunities', 'outreach_status')) {
                $t->string('outreach_status', 16)->default('none')->index();
            }

            // The drafted email itself. Stored split so the manager can
            // edit subject independently of body in the UI.
            if (!Schema::hasColumn('lead_opportunities', 'outreach_draft_subject')) {
                $t->string('outreach_draft_subject', 255)->nullable();
            }
            if (!Schema::hasColumn('lead_opportunities', 'outreach_draft_body')) {
                $t->text('outreach_draft_body')->nullable();
            }

            // Where the draft would be sent. NULL means we couldn't
            // resolve a recipient (synthesiser had only a customer name
            // hint, no email). The UI shows a 'find an email' affordance
            // in that case rather than auto-blocking the lead.
            if (!Schema::hasColumn('lead_opportunities', 'outreach_to_email')) {
                $t->string('outreach_to_email', 255)->nullable();
            }
            if (!Schema::hasColumn('lead_opportunities', 'outreach_to_name')) {
                $t->string('outreach_to_name', 255)->nullable();
            }

            // Timestamps for each gate the draft passes through.
            if (!Schema::hasColumn('lead_opportunities', 'outreach_drafted_at')) {
                $t->timestamp('outreach_drafted_at')->nullable();
            }
            if (!Schema::hasColumn('lead_opportunities', 'outreach_approved_at')) {
                $t->timestamp('outreach_approved_at')->nullable();
            }
            if (!Schema::hasColumn('lead_opportunities', 'outreach_sent_at')) {
                $t->timestamp('outreach_sent_at')->nullable();
            }

            // Who pressed which button. Both nullable until the
            // respective transition fires. We don't FK-constrain on
            // delete because losing a manager's user row shouldn't
            // erase the audit trail — set null is the right move.
            if (!Schema::hasColumn('lead_opportunities', 'outreach_approved_by_user_id')) {
                $t->foreignId('outreach_approved_by_user_id')
                    ->nullable()
                    ->constrained('users')
                    ->nullOnDelete();
            }
            if (!Schema::hasColumn('lead_opportunities', 'outreach_sent_by_user_id')) {
                $t->foreignId('outreach_sent_by_user_id')
                    ->nullable()
                    ->constrained('users')
                    ->nullOnDelete();
            }

            // Free-form notes from the manager when they reject a draft.
            // Useful for "why was this killed?" forensics + future
            // training data on what the team considers off-target.
            if (!Schema::hasColumn('lead_opportunities', 'outreach_reject_reason')) {
                $t->string('outreach_reject_reason', 500)->nullable();
            }

            // Cost/usage stamp from the LLM call. Lets us answer
            // "how much did the outreach drafter cost us last week?".
            if (!Schema::hasColumn('lead_opportunities', 'outreach_draft_cost_usd')) {
                $t->decimal('outreach_draft_cost_usd', 10, 5)->nullable();
            }
        });
    }

    public function down(): void
    {
        Schema::table('lead_opportunities', function (Blueprint $t) {
            $cols = [
                'outreach_status',
                'outreach_draft_subject', 'outreach_draft_body',
                'outreach_to_email', 'outreach_to_name',
                'outreach_drafted_at', 'outreach_approved_at', 'outreach_sent_at',
                'outreach_reject_reason', 'outreach_draft_cost_usd',
            ];
            foreach ($cols as $c) {
                if (Schema::hasColumn('lead_opportunities', $c)) {
                    $t->dropColumn($c);
                }
            }
            // Foreign keys need explicit drop before dropColumn on some drivers.
            foreach (['outreach_approved_by_user_id', 'outreach_sent_by_user_id'] as $fkCol) {
                if (Schema::hasColumn('lead_opportunities', $fkCol)) {
                    $t->dropConstrainedForeignId($fkCol);
                }
            }
        });
    }
};
