<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 2 of the robot vision: each part now belongs to a slot in the
 * robot anatomy (brain, eyes, legs, …) and carries assembly + purpose
 * documentation generated by the CAD agent.
 *
 *   • slot           — RobotBlueprint::SLOT_* the part fills
 *   • purpose        — short markdown explaining what the part DOES
 *                       in the context of the robot
 *   • assembly_notes — markdown describing how to physically attach
 *                       the part to the chassis / its slot
 *
 * Both are populated by the CAD generation phase via the LLM. The
 * shop committee writes the slot when the order is created.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('part_orders', function (Blueprint $t) {
            $t->string('slot', 32)->nullable()->after('agent_key')->index();
            $t->text('purpose')->nullable()->after('description');
            $t->text('assembly_notes')->nullable()->after('design_scad');
        });
    }

    public function down(): void
    {
        Schema::table('part_orders', function (Blueprint $t) {
            $t->dropColumn(['slot', 'purpose', 'assembly_notes']);
        });
    }
};
