<?php

namespace App\Mail;

use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Collection;

/**
 * Daily digest email for one recipient. Dispatched twice per weekday by
 * tenders:send-digest (morning + afternoon slot).
 *
 * The template renders:
 *   • greeting tailored to role (manager sees "everyone", user sees "your")
 *   • sections grouped by urgency bucket (overdue → critical → …)
 *   • per-row action prompts (create SAP opp, set status, state "not-treat"
 *     reason, etc.) generated by Tender::digestPrompts()
 *   • deep-link back to /tenders/{id} so one click lands on the detail page
 */
class TenderDailyDigest extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * @param User $recipient
     * @param 'manager'|'user' $role
     * @param array<string, Collection> $groups urgency_bucket => Collection<Tender>
     * @param int $total total rows in this digest
     * @param 'morning'|'evening' $slot
     */
    public function __construct(
        public User $recipient,
        public string $role,
        public array $groups,
        public int $total,
        public string $slot = 'morning',
    ) {}

    public function envelope(): Envelope
    {
        $prefix  = $this->slot === 'morning' ? 'Concursos da manhã' : 'Concursos final de tarde';
        $urgent  = $this->groups['overdue'] ?? null;
        $urgency = $urgent && $urgent->isNotEmpty()
            ? ' — ' . $urgent->count() . ' em atraso'
            : '';

        return new Envelope(
            subject: "{$prefix} · {$this->total} activos{$urgency}",
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.tenders.daily-digest',
            with: [
                'recipient' => $this->recipient,
                'role'      => $this->role,
                'groups'    => $this->groups,
                'total'     => $this->total,
                'slot'      => $this->slot,
            ],
        );
    }

    public function attachments(): array
    {
        return [];
    }
}
